clear;clc;
%% Step1: ezplot for funciton image
p=ezplot('sin(x)+(cos(x^2-pi/7))^2',[-5*pi,5*pi]);
set(p, 'LineStyle', '-', 'Color', 'black');
xlabel('x');
ylabel('f(x)');
title('Plot for sin(x)+cos^2(x^2-\pi/7)');
%% Step2: using trapz() to estimate the integral
figure;
X = 5:1:500;
Y = zeros(1,496);
for div=5:1:500
    x=linspace(-5*pi,5*pi,div);
    y=sin(x)+(cos(x.^2.-pi/7)).^2;
    Y(div-4)=trapz(x,y);
end
plot(X,Y, 'b-', 'LineWidth',1);
axis auto;

%% Step3: compares to accurate answer generated by integral()
accurate_Y = integral(@(x)sin(x)+(cos(x.^2.-pi/7)).^2, -5*pi, 5*pi);
hold on;
plot(X, repelem(accurate_Y, length(X)));
title('trapz compares to integral');
legend('trapz', 'integral');
xlabel('divisions');
ylabel('result');
%% Conclusion
% From the figure we can derive that integral() is much accurate for
% computing integral in such cases; Also we can find that about 350
% divisions are needed for a converge.
